# Generated by Django 2.2 on 2022-06-21 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.IntegerField(unique=True, verbose_name='Box Number')),
                ('box_description', models.TextField(blank=True)),
                ('box_location', models.CharField(blank=True, max_length=50, verbose_name='Box Location')),
                ('box_creation_date', models.DateTimeField(verbose_name='Box Date')),
            ],
        ),
        migrations.CreateModel(
            name='BoxItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300, verbose_name='Item Name')),
                ('item_quantity', models.CharField(max_length=50, verbose_name='Item Quantity')),
                ('item_creation_date', models.DateTimeField(verbose_name='Item Date')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Box')),
            ],
        ),
    ]
