# Generated by Django 3.2.13 on 2022-07-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20220701_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxitem',
            name='item_quantity',
            field=models.CharField(default=1, max_length=50, verbose_name='Item Quantity'),
        ),
    ]
